### Получение ивентов

GET localhost:8080/events

### Добавление ивентов

POST localhost:8080/events
Content-type: application/json

{
  "title": "Christmas Party",
  "description": "Event for children"
}